### ISSUE TITLE
Support for defaultLocale at runtime/nuxtRuntimeConfig in combination with a Docker Container

### ISSUE THREAD

**Issue by samo4b** [e-Spirit/fsxa-nuxt-module#93]
We are currently using one Docker image and are now trying to use that very same container to deploy to multiple domains.
Locales - en_US, nl_NL, pl_PL, de_DE and so on.

The problem is that the Docker image is being built with the [mandatory](https://github.com/e-Spirit/fsxa-pwa/blob/12be82f74a063444c0679c5183555e62d80c2d43/docs/modules/ROOT/pages/Configuration.adoc) **defaultLocale** which is part of the [IndexPage.vue](https://github.com/e-Spirit/fsxa-nuxt-module/blob/master/src/module/index.ts#L111-L121).
This means we do have one Docker image where the **defaultLocale** is already set (fixed at build time) to (for example) **en_US** but on the **Netherlands (nl_NL) domain** when I access the homepage it results in loading the content in **en_US**.
We don't want to build multiple Docker containers for each domain as they will consume a lot of space.

With [v7.15.1](https://github.com/e-Spirit/fsxa-nuxt-module/commit/ee24e91eec16dcae3c5f176245e4db933df95082) the support to override the **defaultLocale** has been added but I assume this only refers to the build time.

Please correct me if I am wrong but I found no way to get this working on my side and the documentation for the new **FSXA_LOCALE** has not been updated.

**Comment by henczi-espirit** [comment]
Hey Samo,

Thank you for sharing this issue with us.
In our tests we were able to set the FSXA_LOCALE at buildtime of a dockerimage. Meaning, you would need a dockerimage for a deployment each. So our tests confirm your issue with the nuxt-module. While this is fine for most of our customers we understand that it won't fit your requirments.

If creating CI plans for each deployment is no viable solution for you, it sounds like a good feature request, that you can send to our Customer Support team.

sincerely,
Nico

**Comment by samo4b** [comment]
Hi Nico,

Creating CI plans for each rollout is not a viable solution.
With around 30 projects (steadily increasing in the future) the storage could cause an issue for us.
But we asked the Support to create a Feature Request for us.

Greetings,
Sebastian

**Comment by samo4b** [comment]
Hi Nico,

we currently use a workaround for the issue and check if path is `"/"` (which means homepage directly without locale supplied).
The workaround works by adding code in a middleware to redirect the homepage using the fsxa navigation and the `FSXA_LOCALE` which we set during startup (for each project individually).
```
const locale : string = process.env.FSXA_LOCALE || ''
if (locale.length !== 5) return '' // assuming locale is made up like this: en_US e.g.

const navigationResponse : NavigationData | null = await api.fetchNavigation({ locale, initialPath: '/' })
return navigationResponse?.pages.index || ''
```

Greetings,
Sebastian
